### ISSUE TITLE
Update & shade fastparse dependency

### ISSUE THREAD

**Issue by LogicalTime** [unicredit/shocon#23]
Fastparse versions are not binary compatible. I had some errors trying to use the latest version of fast parse with the latest version of shocon.

**Comment by andreaTP** [comment]
This is actually a very good suggestion... Still haven't tried to shade a dependency in sjs

**Comment by andreaTP** [comment]
ok I spent a little time digging around this.
final thoughts and then @evacchi can decide how to proceed:
 - publishing libraries with shaded versions of transitive dependencies is really bad
 - we could do this with sbt-assembly but I do not really feel comfortable with the result

What you @LogicalTime can do is to exclude fastparse from the import of `shocon` itself (e.g. http://www.scala-sbt.org/0.13/docs/Library-Management.html#Exclude+Transitive+Dependencies ).

And then define your import for fastparse.
AFAIK 0.4.X versions are binary compatible, if not we should rise the question in Fastparse itself since minors used to be binary compat.

**Comment by LogicalTime** [comment]
This is from the fastparse github readme:
No binary or source compatibility is guaranteed between any releases. FastParse is still in the 0.x.y phase of development, which means it's still under rapid development and things do change. On the other hand, upgrading is usually trivial, and I don't expect existing functionality to go away.

Any version starting with 0.x.y is not assumed binary compatible on changes. If the first number is not a zero, that is when you can rely on binary compatibility.

**Comment by evacchi** [comment]
should be addressed by #25
